# $TRAVIS_PYTHON_VERSION only available if language = python
language: python

# container based has faster start up
sudo: false

dist: trusty

python:
  - 3.6
  - 2.7

matrix:
  # inherit 1st value by default. So python 3.6
  include:
    - dist: trusty
      sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - BUILDWHEELS=1

    - os: osx
      language: generic
      env:
        - PIP=pip2
        - BUILDWHEELS=1
        - CONDA_OS="MacOSX"

addons:
  apt:
    packages:
      - openmpi-bin

env:
  global:
    - secure: "obtrptOC4ssKOHqwR4dDcFwJYV9JE91E8pvy23zpVVfj+7sXHir+5ebq6AxyoMJUnevI3qakuPW5a/aRlyC+YixZ/24w5UDr6qq7Aa0+fr+VcaH/HQyqMXysq1JuzN3ekGFHRO20XvI055WFzBCJBhIaV9h4hhgWYQCvKlND5gRknaO4DNFdLKwaE6rqW8B/6bD9euGNSsardD26O+GQDDuEH8U6t+mg/3Ulaq8OBbSeejTJxrky+934F4hRt/Y9XCTGl+D5pPmTr+z7yNgsyYvcsqkL/3lH+J0+PWv4rdPhh5eMyI3ZW5wkaInzSuQjGG14KRtoUfniuqrEAis8ILPwKiXA3Uhyrr/7oY+V9IQ3jJm7HIAsfb0tukqVxWgUoQfuahc6y7LexT5wUTV4GefRd9BMzy3JXq1pq/zewwRZfe2rrmjvJxPLNaZQA3bMNcrR2db+2amf0DbxENXmEo8K6nTBCV7Pag/hD1jyD83KhIwIMz8nWnDu0F9YTYAJbyAQm1kh7CfwVdKYK1yXHld7p/d6fkrqv4GHL/1aSPKxAZ9d+3qDC1qWy+B3rQH4+i7tSugIXAMlKddEqwcVu49QFyaFvV3qHmV0jGxWU5CrENjHnVvoXGJybU0eComeBfNuQmPdY8gDtIyNeU63ggR1hLFVCHo6nU6TtDFKLnc="
    # Note: TWINE_PASSWORD is set in Travis settings
    - TWINE_USERNAME=pypmc-travis
    # TODO remove. Just to test if deploying wheels works
    - TRAVIS_TAG=1
    - CONDA_OS="Linux"

script:
  - if [[ $BUILDWHEELS ]]; then
       ./wheels.sh;
    else
       ./travis.sh;
    fi

notifications:
  - email: false
